### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by Qwarkc** [hantang/linuxfromscratch-scripts#1]
Hello there Mr. Hantang. Name's Alex. 
So.. i wanted to ask a question, do i need to include "Step-by-Step" scripts parts in "linuxfromscratch-scripts/lfs/note.md" in the /scripts/12.0-systemd scripts? 
Also, what do i do with commented script parts in chXX.sh? 
Thanks for answering beforehand.

你好 汉唐先生 我叫亚历克斯。
我想问一个问题，我是否需要在 /scripts/12.0-systemd 脚本中加入 "linuxfromscratch-scripts/lfs/note.md "中的 "Step-by-Step "脚本部分？
此外，我该如何处理 chXX.sh 中的注释脚本部分？
感谢您的预先答复。

**Comment by hantang** [comment]
@Qwarkc A good way is read the Document of `Linux From Scratch` first, and execute the command step by step. 
Why I create this script(`python html2scripts.py`) is to reduce some repetitive copy-paste works, and to record some common error solutions.

So, if you use this, you just run "Step-by-Step" parts in your linux terminal manually after create `scripts/xx.sh`. 
And "Step-by-Step" parts include command like `sh $mysrcdir/ch09.sh` already, which is from `/scripts/12.0-systemd` directory.
Comments in "Step-by-Step" are explanations what you are doing, like `# run manually` means you need copy `chXX.sh` and run it in terminal.

As for commented script parts in chXX.sh, most of that are test part, 
and other are delimiters(like `# -------`, `# 10.4.`(chapters), `# tar -xf XX and cd XX`). 
If you run failed, look the difference from LFS Document and the `chXX.sh`, and fix something.
